version: "3"
services:
  app:
    restart: always
    build: .  # '点'代表当前目录
    command: bash -c "python3 manage.py collectstatic --no-input && gunicorn --worker-class=gevent -b 0.0.0.0:8000 XSite.wsgi:application"
    volumes:
      - .:/xsite
      - static-volume:/frontend/static
      - /media/xsite:/media/xsite
      - /logs/xsite:/logs/xsite
    expose:
      - "8000"
    depends_on:
      - db
    networks:
      - web_network
      - db_network
  db:
    image: mysql:8.0
    volumes:
      - "/var/lib/mysql:/var/lib/mysql"
    ports:
      - "3306:3306"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=xsite
    networks:
      - db_network
  nginx:
    restart: always
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static-volume:/frontend/static
      - /etc/nginx:/etc/nginx
      - /media/xsite:/media/xsite
    depends_on:
      - app
    networks:
      - web_network

networks:
  web_network:
    driver: bridge
  db_network:
    driver: bridge

volumes:
  static-volume: