# Generated by Django 3.0.1 on 2020-01-07 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='articleseries',
            table='article-series',
        ),
    ]
