# Generated by Django 3.0.1 on 2020-01-07 14:46

import article.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20200107_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.FileField(upload_to='articlefiles/%Y/%m/%d/', verbose_name='文章内容文件'),
        ),
    ]
