# Generated by Django 3.0.1 on 2020-01-07 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_remove_article_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content',
            field=models.FileField(default=1, upload_to='articlefiles/%Y/%m/%d/', verbose_name='文章内容文件'),
            preserve_default=False,
        ),
    ]
