# Generated by Django 3.0.1 on 2020-01-07 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_article_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
