# Generated by Django 3.0.1 on 2020-01-07 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_delete_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('summary', models.CharField(max_length=1000, verbose_name='摘要')),
                ('content', models.FileField(upload_to='articlefiles/%Y/%m/%d/', verbose_name='文章内容文件')),
                ('read_num', models.PositiveIntegerField(default=0, verbose_name='阅读量')),
                ('visible', models.BooleanField(default=True, verbose_name='可见性')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_datetime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('label', models.ManyToManyField(blank=True, to='article.ArticleLabel')),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='article.ArticleSeries', verbose_name='文章系列')),
            ],
            options={
                'verbose_name': '文章',
                'db_table': 'article',
            },
        ),
    ]
