# Generated by Django 2.2.5 on 2020-03-21 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='like_num',
            field=models.PositiveIntegerField(default=0, verbose_name='点赞量'),
        ),
    ]
