# Generated by Django 3.0.4 on 2020-04-20 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_articleseries_bgi_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleseries',
            name='bgi_url',
            field=models.CharField(max_length=200, verbose_name='背景图片URL'),
        ),
    ]
