# Generated by Django 3.0.4 on 2020-04-02 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userextend',
            options={'verbose_name': '用户扩展'},
        ),
        migrations.AlterField(
            model_name='userextend',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatar/%Y%m%d/', verbose_name='头像'),
        ),
    ]
