# Generated by Django 3.0.4 on 2020-04-10 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_userextend_avatar_other'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextend',
            name='github_user_id',
            field=models.IntegerField(null=True, unique=True, verbose_name='Github用户ID'),
        ),
    ]
