# Generated by Django 3.0.4 on 2020-04-10 21:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0009_article_like_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标志')),
                ('is_read_by_author', models.BooleanField(default=False, verbose_name='作者已读标志')),
                ('is_read_by_reader', models.BooleanField(default=False, verbose_name='读者已读标志')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_datetime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('article_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', related_query_name='comment', to='article.Article', verbose_name='文章ID')),
                ('parent_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='comment.Comment', verbose_name='父评论ID')),
                ('to_user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='回复评论对象用户ID')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', related_query_name='comment', to=settings.AUTH_USER_MODEL, verbose_name='发表评论用户ID')),
            ],
            options={
                'verbose_name': '评论',
                'db_table': 'comment',
            },
        ),
    ]
